site_name: OSPSD-Spring-26 Documentation
nav:
  - Home: index.md
  # Add more pages as you create them:
  # - Cloud Storage API: cloud_storage_client_api.md
  # - GCP Impl: cloud_storage_client_impl.md